### ISSUE TITLE
migrate gogs-to-gitlab

### ISSUE THREAD

**Issue by hero9** [dorianboulch/gogs-to-gitlab#1]
Hi!
Could u pls provide me template of running project?
Also, template of URL of repo for gogs and gitlab...

Cheers!
Galym

**Comment by dorianboulch** [comment]
Hello

You can follow the instruction of the README.md to make it work.
By the way, there is a lack of documentation about the env variables.
You should copy the `src/.env.dist` to `src/.env` and adjusting the urls in `src/.env`.

Does it helps you ?

**Comment by hero9** [comment]
When I'm gonna run the project i should type:
```
node index.js repoName1 repoName2
```

Is it correct?

Now I have the problem that your script can't find the repos from gogs and gitlab
Path:
```
https://try.gogs.io/api/v1/repos/gogs-to-gitlab
Repo "gogs-to-gitlab" not found in gogs
```

**Comment by dorianboulch** [comment]
Yes it is correct.
You have to write the full namespace of your repository in both sides.
For example : `node index.js yourname/gogs-to-gitlab yourname/gogs-to-gitlab`

**Comment by hero9** [comment]
Ok, it worked for me)
But it only migrate the first message in issue, no photos, no comments((((((
Could you pls add this functionality??
Thanks)

**Comment by dorianboulch** [comment]
The feature you are asking for needs a new issue.
